// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmb55PT_U3XBMeeU21VHiArgL1f8e2pVE',
    appId: '1:576794980755:web:a2175243f392aedf5fb866',
    messagingSenderId: '576794980755',
    projectId: 'yaan-12663',
    authDomain: 'yaan-12663.firebaseapp.com',
    storageBucket: 'yaan-12663.firebasestorage.app',
    measurementId: 'G-0T65RHFZBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLfliBvRFlXECmlOvkwEqYWwNnMCxIPpU',
    appId: '1:576794980755:android:0d72ffc2696793b35fb866',
    messagingSenderId: '576794980755',
    projectId: 'yaan-12663',
    storageBucket: 'yaan-12663.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxfdkFRMnVfy92ckN3aDLnd-ST8VOF7Hw',
    appId: '1:576794980755:ios:0bbf7a11c04d05fe5fb866',
    messagingSenderId: '576794980755',
    projectId: 'yaan-12663',
    storageBucket: 'yaan-12663.firebasestorage.app',
    iosBundleId: 'com.example.yaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxfdkFRMnVfy92ckN3aDLnd-ST8VOF7Hw',
    appId: '1:576794980755:ios:0bbf7a11c04d05fe5fb866',
    messagingSenderId: '576794980755',
    projectId: 'yaan-12663',
    storageBucket: 'yaan-12663.firebasestorage.app',
    iosBundleId: 'com.example.yaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmb55PT_U3XBMeeU21VHiArgL1f8e2pVE',
    appId: '1:576794980755:web:bcf41d05ceb3a35b5fb866',
    messagingSenderId: '576794980755',
    projectId: 'yaan-12663',
    authDomain: 'yaan-12663.firebaseapp.com',
    storageBucket: 'yaan-12663.firebasestorage.app',
    measurementId: 'G-VSEMPCZBVS',
  );
}
